# Generated by Django 5.1.6 on 2025-06-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_filme_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='filme',
            name='atores',
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='atores',
            field=models.ManyToManyField(blank=True, related_name='filmes', to='filmes.ator'),
        ),
    ]
